
SW.SnowSettings = { "simpleweather/textures/snow_0_01" , "simpleweather/textures/snow_0_01_normal" , "snow" }
SW.HideInSnowSettings = { "1" , "no_decal" }

SW.SnowTextureSettings = {}
-- A
SW.SnowTextureSettings["ajacks/ajacks_grass-dirt01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["ajacks/ajacks_grass-sand01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["ajacks/ajacks_grass01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
-- B
SW.SnowTextureSettings["blend/blend_conf_dirtgrass"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["blend/blend_conf_acliffgrass"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
-- C
-- SW.SnowTextureSettings["cs_havana/pavement001a"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["cs_havana/ground01grass"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["cs_havana/groundd01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["customtext/gc textures/blends/grass_dirt_blend04"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
-- D
-- SW.SnowTextureSettings["de_aztec/ground02_blend_nobump"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_cbble/grassdirt_blend"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_cbble/grassfloor01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_chateau/brusha"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_chateau/groundd"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_chateau/groundd_blend"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_chateau/groundl"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_chateau/rockf_blend"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_dust/groundsand_blend"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_dust/groundsand03"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_dust/rockwall_blend"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_nuke/nukblenddirtgrass"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_nuke/nukblenddirtgrassb"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_piranesi/pi_ground"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_piranesi/pi_ground_blend"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_tides/blendgrassstonepath"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_tides/tides_grass_a"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["de_train/blendgrassdirt001a"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["dm_stad/floor/grass03"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["dm_stad/floor/blendgrassgrass01"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["dm_stad/floor/blendgrassdirt02"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["dm_stad/floor/blendgrassforest01"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
-- F
SW.SnowTextureSettings["fork/cliff04c"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["fork/cliff04c_skybox"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["freespace/terrain/freespace_dirtgravelblend01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["freespace/terrain/freespace_dirtrockblend01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["freespace/terrain/freespace_grassdirtblend01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["freespace/terrain/freespace_grassrockblend01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["freespace/terrain/freespace_skyboxterrainblend01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
-- G
SW.SnowTextureSettings["gm_construct/grass_13"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["gm_construct/flatgrass"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["gm_construct/flatgrass_2"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["gm_construct/grass-sand_13"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["gm_vernrock/blends/blendgrassdirt001"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["gm_vernrock/blends/blendgrassmud001"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["gpoint/fixedgrass/dirtfloor006a"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["ground/flash_ground_blend"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["ground/flash_ground_skyboxtrees"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["ground/skybox_ground01_blend"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["ground/hr_g/hr_gravel_grass_001_blend"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["gulch/gulch_cavegrass"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["gulch/gulch_cavesand"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["gulch/gulch_cavewall" ] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["gulch/gulch_dirtgrass"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["gulch/gulch_rockgrass"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["gulch/gulch_rocksand"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["gulch/gulch_sandgrass"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
-- L
SW.SnowTextureSettings["lostcoast/nature/blendpathweeds002a"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["lostcoast/nature/blendrockgravel002a"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["lostcoast/nature/blendstonepathweeds001a"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
-- M
SW.SnowTextureSettings["majoris/buhriz_lightsand_01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["majoris/buhriz_darksand_01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["majoris/buhriz_sandrock_01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["majoris/buhriz_sandgrass_02"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/de_aztec/de_aztec/ground01_blend_-272_-960_-151"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/de_aztec/de_aztec/ground01_blend_-2689_259_-247"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/de_aztec/de_aztec/ground01_blend_-2705_-776_-161"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/de_aztec/de_aztec/ground02_blend_-272_-960_-151"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/de_aztec/de_aztec/ground02_blend_-424_-1484_-157"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/de_aztec/de_aztec/ground02_blend_-976_699_-119"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-1824_-8_-328"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-2184_0_-328"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-312_-72_-232"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-464_-1088_-296"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-88_56_-232"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_320_72_-232"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_664_32_-232"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_704_-352_-248"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_720_-760_-248"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_1008_-1176_-288"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_1248_-1264_-288"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_864_-992_-304"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-384_-1848_-336"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-768_-2048_-336"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-384_-2128_-336"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_56_-2160_-368"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_1280_-2032_-368"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_1712_-576_-288"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_1384_-384_-288"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_1344_-96_-288"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_1992_-320_-288"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_1400_528_-288"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_1384_912_-216"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_1376_1208_-216"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_1168_1216_-216"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_1168_1440_-216"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_1152_1712_-216"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_864_1544_-216"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_464_1704_-248"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_128_1728_-248"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_208_1144_-248"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_680_640_-232"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_184_856_-248"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-24_832_-312"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-256_944_-312"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-608_816_-312"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-976_656_-312"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-1056_992_-312"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-976_656_-312"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-976_384_-312"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-496_1024_-280"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-2280_-392_-328"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-1280_-32_-312"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-1088_-272_-312"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-1464_-684_-276"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-1448_-752_-160"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobbledirt002a_-1072_80_-312"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobblegrass002a_-2280_-392_-328"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobblegrass002a_496_-2176_-368"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendcobblegrass002a_2040_-872_-288"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendstonedirt001a_336_-1824_-336"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/dod_jagd/stone/blendstonedirt001a_1656_-1120_-288"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/gm_apehouse_summer_day/nature/blendgrassdirt01_wvt_patch"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/gm_iremia/nature/blendgrassdirt02_noprop_wvt_patch"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/gs_camp_killpact_v1/freespace/terrain/freespace_grassdirtblend01_wvt_patch"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/gs_camp_killpact_v1/freespace/terrain/freespace_grassrockblend01_wvt_patch"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/karam/blend_grass_road"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/karam/blend_grass_sand"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/karam/blend_riverbed_grass"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/karam/blend_rock_grass2"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/karkar/blend_sand_road"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/karkar/blend_sand_road_skybox"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/karkar/blend_sand_gravel"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/karkar/blend_rock_sand"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/karkar/blend_rock_sand_skybox"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/karkar/blend_sand_coal"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/road/asphalt_sand_blend02"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/road/blend_sand_road_vil"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/road/blendsand01road_fmp"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/road/ramadisandroad_dirt"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/road/ramadisandsidewalk_oog"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/baghdad_blend_07"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/blend_dirt_sand_1024_era2_detail"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/blend_cobble_sand_1024_era1_detail"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/blend_road_sand_1024_era2"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/blend_dirt_sand_1024_era2_curb"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/blend_dirt_sand_1024_era2"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/blend_road_sand_1024_era1"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/blend_rubble_sand_1024_era1"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/blend_stone_sand_1024_era1"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/blend_tile_sand_1024_era1"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/rp_evocity2_v5p/nature/blendgrassdirt01_noprop_wvt_patch"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/rp_evocity2_v5p/nature/blendgrassdirt02_noprop_wvt_patch"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/rp_truenorth_v1a/statua/nature/blendgrassdirt01_wvt_patch"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/rp_unioncity_day/unioncity/natural/parkgrassleaves_wvt_patch"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/baghdad_blend_01"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/baghdad_blend_02"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/blend_grass_sand_1024_era1"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/sand_grass_blend_mino"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/baghdad_blend_03"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/blend_sand_rock_mino"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/sand_blend01_mino"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/sand_blend02_mino"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/sand_sidewalk_blend_mino"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/sand_sidewalk02_blend_mino"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/grass_sand_01blend_stw"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/stones_sand_01blend_stw"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/blend_grass_dirt_1024_era1_detail"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maps/terrain/sand01a_mino"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["maxofs2d/grass_01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["models/props_gulch/grassfloor002a"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["models/statua/shared/blendgrassdirt01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
-- N
SW.SnowTextureSettings["nature/anzio_grass_blend002"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/argentan_blendcobblegrass"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/argentan_blendgrassdirt"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/argentan_blendgrassdirt_cheap"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/argentan_skygrasstrees"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgrassgrass001a"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgrassgravel01"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgravelgravel01"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendmilground008_2"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendmilground008_2_plants"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendmilground008b_2"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendsandgrass008a"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendsandsand008a"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendcobblegrass002"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgrassdirt01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgrassdirt01_noprop"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgrassdirt02"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgrassdirt02_noprop"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgrassdirt03"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgrassgravel001a"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgrassgravel001b"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgrassgravel002b"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgrassmud01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgrasspave01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgravelconc01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgravelgravel02"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgravelmud01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgravelmud02"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendmilground008_4"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendmilground008_8b"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/dirtfloor006a"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/forest_grass_01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/grassfloor001a"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/grassfloor002a"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/grassfloor003a"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/infblendgrassdirt001a"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/milground002"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/anzio_skytrees"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/argentan_blendcliffgrass"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendcobbledirt001"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blenddirtgrass001b"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blenddirtgrass008a"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blenddirtgrass008b"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blenddirtgrass008b_lowfriction"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blenddirtgravel01"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgrassgravel001c"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgrassgravel003a"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendgravelgravel02b"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendmilground004_2"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendmilground005_2"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendmilground011_2"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendmilrock002_ground002"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendprodconcgrass"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendproddirtgrass"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendrockgrass004a"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendsandsand008b"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blendsandsand008b_antlion"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/grass_whitemosspebbles_blend"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/nijo_grasstogravel_ivy"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/nijo_grasstogravel2_ivy"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/red_grass"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/rockwall1_grass_ivy"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/pinkleaftograssblend_ivy"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/blend_ivy1"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["nature/short_red_grass"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
-- R
SW.SnowTextureSettings["rubble/blendrubblegrass001b_avalanche"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
-- S
SW.SnowTextureSettings["sgtsicktextures/blend_chipsgrass_001"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["statua/nature/blendforest_01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["statua/nature/blendforest_02"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["statua/nature/blendgrassdirt01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["statua/nature/blendgrasssand01"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["statua/nature/farmblend1"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["statua/nature/farmblend2"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["statua/nature/farmblend3"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["statua/nature/farmblend4"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["statua/nature/rockfordgrass2_noprop"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["statua/nature/rockfordgrass1"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
-- T
SW.SnowTextureSettings["theprotextures/blendgrassgravel002a_gmfix"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["textures/enviroment/blendgrassgravel1"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["textures/enviroment/blendsandgrass1"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["trakpak/terrain/blendgrassballast"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
-- U
SW.SnowTextureSettings["unioncity/floorground/parkcobbles"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["unioncity/natural/parkgrassleaves"] = { 0 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["unioncity2/floors/grass"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["unioncity2/floors/parkcobbles"] = { 1 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
SW.SnowTextureSettings["unioncity2/floors/parkdirttograss"] = { 2 , SW.SnowSettings[1] , SW.SnowSettings[2] ,SW.SnowSettings[3] }
-- Stuff That Gets Hidden
-- SW.SnowTextureSettings["de_chateau/bush01a"] = { 3 , SW.HideInSnowSettings[1] , SW.HideInSnowSettings[2] }
-- SW.SnowTextureSettings["models/cliffs/ferns01"] = { 3 , SW.HideInSnowSettings[1] , SW.HideInSnowSettings[2] }
-- SW.SnowTextureSettings["models/props_foliage/bush"] = { 3 , SW.HideInSnowSettings[1] , SW.HideInSnowSettings[2] }
-- SW.SnowTextureSettings["models/props_foliage/grass_clusters"] = { 3 , SW.HideInSnowSettings[1] , SW.HideInSnowSettings[2] }
-- SW.SnowTextureSettings["models/props_foliage/grass3"] = { 3 , SW.HideInSnowSettings[1] , SW.HideInSnowSettings[2] }
-- SW.SnowTextureSettings["models/props_foliage/rocks_vegetation"] = { 3 , SW.HideInSnowSettings[1] , SW.HideInSnowSettings[2] }
-- SW.SnowTextureSettings["models/props_forest/fern01"] = { 3 , SW.HideInSnowSettings[1] , SW.HideInSnowSettings[2] }
-- Stuff That Has Unique Swaps
-- SW.SnowTextureSettings["apehouse/nolight_skybox_farms_summer"] = { 1 , "xmas_apehouse/skybox_farms_winter_nolights" } -- gm_apehouse
-- SW.SnowTextureSettings["apehouse/mountain_blend" , 0 , "xmas_apehouse/snow_mountain_blend" } -- gm_apehouse
-- SW.SnowTextureSettings["models/fork/tree_pine04_lowdetail_cluster_card"] = { 1 , "models/props_foliage/tree_pine_cards_01_snow" } -- needs custom texture
-- SW.SnowTextureSettings["models/fork_gs/tree_pine04_lowdetail_cluster_card"] = { 1 , "models/props_foliage/tree_pine_cards_01_snow" } -- needs custom texture
SW.SnowTextureSettings["models/props_foliage/arbre01"] = { 1 , "models/props_foliage/arbre01_snow" }
SW.SnowTextureSettings["models/props_foliage_gs/arbre01"] = { 1 , "models/props_foliage/arbre01_snow" }
SW.SnowTextureSettings["models/fork/tree_pine04_lowdetail_cluster"] = { 1 , "models/props_foliage/arbre01_snow" }
SW.SnowTextureSettings["models/fork_gs/tree_pine04_lowdetail_cluster"] = { 1 , "models/props_foliage/arbre01_snow" }
SW.SnowTextureSettings["models/props_foliage/arbre01_b"] = { 1 , "models/props_foliage/arbre01_b_snow" }
SW.SnowTextureSettings["models/props_foliage/hedge_128"] = { 1 , "models/props_foliage/hedgesnow_128" }
SW.SnowTextureSettings["models/props_foliage_gs/hedge_128"] = { 1 , "models/props_foliage/hedgesnow_128" }
SW.SnowTextureSettings["models/props_foliage/tree_pine_cards_01"] = { 1 , "models/props_foliage/tree_pine_cards_01_snow" }
